language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -r requirements-ci.txt
script:
  - make test-cov
after_success:
  - codecov
